### ISSUE TITLE
Maybe a few issues?

### ISSUE THREAD

**Issue by maddovr** [panr/gatsby-starter-hello-friend#1]
Great work porting this theme to gatsby, I've encountered a few issues so maybe you could help me.
- I selected default theme light in `gatsby-config.js`, but dark is still the default;
- If there is no post with a coverImage, GraphQL throws out an error, if there is even one post with a coverImage, it works flawlessly;
- You cannot insert an `<a>` tag in `gatsby-config.js` for the footer, you have to manually edit the `layout.js` file;
- If you insert a logo in `gatsby-config.js`, the title won't appear anymore;
- I modified `SEO.js` file in order for it to have the lang-meta-keywords attribute, but it doesn't seem to work (it's not recognized in the final build);
- Remark (gatsby markdown parser), offers options for the excerpt to be specified just like any other markdown parser with `<!-- more-->`, is there a reason to do so in the front matter?
- Lack of blog features (tags, categories, search and comments)?
- If you use line numbers in prismjs, you will notice that line numbers two digits and beyond are being cut by the margins;

There are many things in the list I'm aware, but I think your theme has a very minimal yet elegant design, but unfortunately as I'm busy with my university exams, I'll not be able to help till next month at least. Thank you for your great work anyway.

**Comment by panr** [comment]
Hi @maddovr I'll look at these issues in upcoming weekend. Probably you're right and some of the config related issues don't work, I'll fix it! ;-)

> If there is no post with a coverImage, GraphQL throws out an error, if there is even one post with a coverImage, it works flawlessly;

Huh, interesting 🤔 

> I modified `SEO.js` file in order for it to have the lang-meta-keywords attribute, but it doesn't seem to work (it's not recognized in the final build);

I thought this should work out of the box... Sorry, I'll check it.

> Lack of blog features (tags, categories, search and comments)?

Yes, I know... These will come in next major release 👌

**Comment by maddovr** [comment]
Another two suggestions that comes to mind that should be fairly easy to do:

- I truly like the font choice, it'a very light and readable typeset, however I do not really understand why shipping the .woff format instead of the .woff2 format. It's a free ~200KB size reduction for the downloaded bundle, and compatibility shouldn't really matter since [it's pretty compatible with everything but ie11](https://caniuse.com/#feat=woff2);
- I think splitting the footer in a different component would be helpful as many blogs/websites are now required to add stuff like cookie alerts and privacy policies somewhere and that's 80% of the time done in the footer. Moreover it would allow for easier customization (for example, if you want to add a few social links at the bottom of the blog);
Once again, I'm sorry for blabbering without contributing, it's not my style tbh, but I truly lack the time atm, hope I can in the not so distant future XD

**Comment by panr** [comment]
@maddovr 

> * If there is no post with a coverImage, GraphQL throws out an error, if there is even one post with a coverImage, it works flawlessly;

Do you know how to fix it? 😱 I can't figure it out... 😭 Should I create a custom field with default value in gatsby-node?

**Comment by maddovr** [comment]
I'll think about it when I return home, I'll also review the PR I made with your suggested changes in a few days time (I'm currently abroad). Should be simple with just tweaking the GraphQL queries, but I need to look at it first. Two more issues I should mention:
- Links are basically invisible in the body unless you hover/click on them
- Correct favicons options are absent.

**Comment by panr** [comment]
Thanks for catching these issues. I fixed most of them 👍
