### ISSUE TITLE
GraphQL Error: Unknown argument 'formatString'

### ISSUE THREAD

**Issue by jmsv** [panr/gatsby-starter-hello-friend#15]
Hi, this starter looks really nice! Unfortunately I'm running into this error when I try to get it running. I've tried:

```bash
gatsby new gatsby-starter-hello-friend https://github.com/panr/gatsby-starter-hello-friend
cd gatsby-starter-hello-friend
npm run dev
```

but I get the following GraphQL error from `src/templates/tags.js`:

> Unknown argument 'formatString'

---

### Screenshot

![error screenshot](https://user-images.githubusercontent.com/14852491/67583388-658b2c80-f743-11e9-95c7-5d93e554b900.png)

**Comment by BoltzmannBrain** [comment]
Also running into this. It did not work to edit the three `date(formatString: "YYYY-MM-DD")` entries and make sure the dates in all markdown files match.

Please help @panr, thanks!

**Comment by panr** [comment]
Shiet... I'll get back to you soon with answers 🙏

**Comment by panr** [comment]
Hmm... Strange... I executed the same code @jmsv you mentioned and everything works on my machine 🤔 I use `yarn` and `node 11.10.1`... Did I miss something here?

Also... Does `npm install / yarn install` help?

**Comment by BoltzmannBrain** [comment]
Sorry for the delay but I tracked this down to incompatible node version: v12+ results in this failure. [Dialing back node](https://medium.com/@katopz/how-to-install-specific-nodejs-version-c6e1cec8aa11) to v10.17.0 works for me!

**Comment by panr** [comment]
Huh, that's interesting. I also have v12+ 🤔

**Comment by rendiwijiatmoko** [comment]
Im stil stack with this problem

**Comment by sauware** [comment]
same problem with nodejs v11.15.0 and 6.7.0

**Comment by soenkewindhausen** [comment]
same problem with nodejs v12.9.0 and npm 6.13.1
starter looks great. thanks for the help

**Comment by panr** [comment]
### 😟

What Gatsby version do you have? Maybe that will help debug this...

**Comment by sauware** [comment]
Gatsby 2.8.18. thanks.

**Comment by soenkewindhausen** [comment]
I have Gatsby 2.15.1 
Thank you

**Comment by TBooty** [comment]
Following this PR resolved the issue for me:
https://github.com/panr/gatsby-starter-hello-friend/pull/10

**Comment by panr** [comment]
Damn it, I totally forgot about this PR... 
OK, today after work I'll check everything again and if it really fixes the issue, I'll merge it and gonna let you know...

Sorry for that, my time is very limited at the end of the year 😢

**Comment by panr** [comment]
Sooner that I thought — PR fixing those errors has been merged. I hope it fixes the problem 😬 

Let me know!

**Comment by soenkewindhausen** [comment]
It worked thank you!!!

**Comment by panr** [comment]
It's thanks to @fwojciec and @TBooty 🙌 

Thank you guys! 🎉
