### ISSUE TITLE
RSS Feed?

### ISSUE THREAD

**Issue by eneim** [panr/gatsby-starter-hello-friend#17]
Hi there. It seems that your starter doesn't support RSS feed. I tried to (merely) add 'gatsby-plugin-feed' plugin and it doesn't work out of the box so I wonder if this starter needs some manual work to do. Can you help to advise? Thanks :D.

**Comment by panr** [comment]
Is it still a problem? You closed the issue 🤔

**Comment by eneim** [comment]
@panr It is Ok now. The guideline in plugin page is not enough but there is better one in "adding feed to your site" page which helps.

**Comment by panr** [comment]
Cool!
