### ISSUE TITLE
Installation Instructions?

### ISSUE THREAD

**Issue by slimandslam** [panr/gatsby-starter-hello-friend#3]
Are there installation instructions somewhere? I don't see them.

**Comment by panr** [comment]
HI @slimandslam first you clone to clone repo:

`git clone https://github.com/panr/gatsby-starter-hello-friend.git`

then switch to directory where you keep this repo, probably just:

`cd gatsby-starter-hello-friend`

and for starting localhost server:

`gatsby develop`

and in browser go to `localhost:8000`.

**Comment by mkempster22** [comment]
Following the installation instructions I only get 

`Gatsby.js development 404 page
There's not a page yet at /about

Preview custom 404 page

Create a React.js component in your site directory at src/pages/about.js and this page will automatically refresh to show the new page component you created.

If you were trying to reach another page, perhaps you can find it below.`

the 404 page works fine but all other pages including the about page that is pre created don't work

**Comment by panr** [comment]
@mkempster22 hard to say, what's wrong... I've just cloned this repo again to find out if there's something wrong with the setup, but everything... works on my machine... 

Try to add `src/page/index.js` as an empty file and let me know if this works, ok?

**Comment by mkempster22** [comment]
Looks like i'm getting an error during runtime for a plugin. I'll have a look round whats wrong with my installation

```
ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPages lifecycle:

Cannot return null for non-nullable field Frontmatter.path.
```

**Comment by jyoo** [comment]
It would be quite late, but I had encountered the exact same error. 
```
 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPages lifecycle:

Cannot return null for non-nullable field Frontmatter.path.



  Error: Cannot return null for non-nullable field Frontmatter.path.

failed createPages - 0.034s
```

In my case, I added some posts in `posts` directory before running `gatsby build`. For some posts, I forgot to add `path` in the Front Matter. Checking Front Matter in your posts might be helpful!

**Comment by panr** [comment]
Did you set a `path` value in frontmatter? It looks like you have `null` (= is empty)
